### ISSUE TITLE
Interested in the thesis!

### ISSUE THREAD

**Issue by zyklotomic** [larandaA/hgraphs#1]
I was wondering if the thesis is publicly available? I tried Googling, but to no avail.

@snowleopard I found this repo because I saw that you starred it, and I am a huge fan of your alga library too. How did you stumble across this repo?

**Comment by snowleopard** [comment]
I learned about this library because the thesis referenced my algebraic graphs paper -- I got a notification from Google Scholar :)

The thesis is available [here](https://elib.bsu.by/bitstream/123456789/246700/1/%d0%90%d0%a1%d0%9e%d0%91%d0%9e%d0%98_%d0%a0%d1%8b%d0%b6%d0%b5%d0%b2%d0%b8%d1%87_2020.pdf). I read it but it's in Russian, so you might find it somewhat more challenging! The good news is that the main ideas are all implemented here as a Haskell library, and the code is pretty readable, e.g.:

https://github.com/larandaA/hgraphs/blob/322b5cdfafbae851b4251c907e2c81b82cf02d4a/src/Data/Graph/Abstract/Algorithm/MaxFlow.hs#L11-L21
